[plugin]
repository = "https://github.com/dohwaplugins/Dalamud-VFXEditor.git"
commit = "acdaf8a9232a101fab87586f530ae13c5f79a359"
owners = [
    "KangDohwa",
    "0ceal0t",
]
project_path = "VFXEditor"
