[plugin]
# The open-source Git repository that your code is hosted on.
# Must be visible to the external web, but doesn't have to be GitHub.
# If `git clone` accepts it, it will work here, with the caveat that it
# must be accessible (i.e. no `git` or `ssh` URLs, as the agent cannot clone those)
repository = "https://github.com/dohwaplugins/EnmityHp.git"
# The commit to check out and build from the repository.
commit = "2c495026819e3411069eb94b0ed0dd2a3a58eae5"
# The people authorised to update this manifest (e.g. who can deploy updates). These are GitHub usernames.
owners = [
    "KangDohwa"
]
