[plugin]
repository = "https://github.com/dohwaplugins/umbra.git"
commit = "befe79aed42bc05fc239596b801e054a671bd5d1"
owners = [
		"KangDohwa",
		"haroldiedema",
]
project_path = "Umbra"
changelog = """
 - Fixed the settings window from rebinding events more than once.
"""
