[plugin]
repository = "https://github.com/dohwaplugins/umbra.git"
commit = "f735bc3d20719465f5f08e6e22c57bb0b47336c7"
owners = [
		"KangDohwa",
		"haroldiedema",
]
project_path = "Umbra"
changelog = """
 - Fixed the settings window from rebinding events more than once.
"""
