[plugin]
repository = "https://github.com/dohwaplugins/KingdomHeartsPlugin.git"
commit = "2e926277dd3a6d5fc9736abb077ff6497eaacb1f"
owners = [
    "KangDohwa",
    "Arrenton",
]
project_path = "KingdomHeartsPlugin"
changelog = """
Added scale feature for class icon.
Class icons use HD texture now.
"""
