[plugin]
repository = "https://github.com/dohwaplugins/Accountant.git"
commit = "7cce41d485d4a95447691de437cd6723e619c817"
owners = [
    "KangDohwa",
    "Ottermandias",
]
project_path = "Accountant"
