[plugin]
repository = "https://github.com/dohwaplugins/Dalamud.FullscreenCutscenes.git"
commit = "6191823fd2d5666c1f2d5a94a5ee245c5b88f144"
owners = [
    "KangDohwa",
    "goaaats",
]
project_path = "Dalamud.FullscreenCutscenes"
