[plugin]
repository = "https://github.com/dohwaplugins/FantasyPlayer.git"
commit = "1176b99bad96823ae46a5a568e27e5b3a1be2948"
owners = [
    "KangDohwa",
]
project_path = "FantasyPlayer"
version = "2.2.0.2"
changelog = """\
**Bug Fixes**
- Fixes so that the plugin disposes properly
- The browser should now open using the same method Dalamud uses for logging in, Linux/Mac OSX users see if you can login now
"""
