[plugin]
repository = "https://github.com/dohwaplugins/Dalamud.DiscordBridge.git"
commit = "a8a592c5eb591b6bce25fb8e0c2860ebb6696af1"
owners = [
    "KangDohwa",
    "reiichi001",
		"goaaats",
]
project_path = "Dalamud.DiscordBridge"
changelog = """
Updated for API 9.
"""
