[plugin]
repository = "https://github.com/dohwaplugins/EzMiniCactpot.git"
owners = [
		"KangDohwa",
		"daemitus",
		"MidoriKami"m
]
project_path = "MiniCactpotSolver"
commit = "0764fcc25b49fff26da45638640f46c33d9ed50c"
