[plugin]
repository = "https://github.com/dohwaplugins/DeviceChangeFix.git"
commit = "4c468b79156bd21ca147130410f90cc891a95ddd"
owners = [
    "KangDohwa",
		"Jessidhia",
]
project_path = "DeviceChangeFix"
changelog = "Update to API 9"