[plugin]
repository = "https://github.com/dohwaplugins/GatherBuddy.git"

# The commit to check out and build from the repository.
commit = "aee2446dc403dacd6f033a4b657aa4f957a1417f"

# The people authorised to update this manifest (e.g. who can deploy updates). These are GitHub usernames.
owners = [
    "KangDohwa"
]

# Optional: where your project/csproj is located within the repository.
# If empty or unspecified, it will be assumed the project is in the root of the repository.
project_path = "GatherBuddy"

# The changelog for this version. Will be shown in-game, as well on the Goat Place Discord.
changelog = """\
		Update for KR\
		"""
