[plugin]
repository = "https://github.com/dohwaplugins/GatherBuddy.git"
commit = "757f0a3bbdf81bc7b952bf10a2201a3bb0535fc0"
owners = [
    "KangDohwa",
    "Ottermandias",
]
project_path = "GatherBuddy"