[plugin]
repository = "https://github.com/dohwaplugins/DamageInfoPlugin.git"

# The commit to check out and build from the repository.
commit = "e83a31ba1bd5cef7375517a51b2069c5c6ba9f4c"

# The people authorised to update this manifest (e.g. who can deploy updates). These are GitHub usernames.
owners = [
    "KangDohwa"
]

# Optional: where your project/csproj is located within the repository.
# If empty or unspecified, it will be assumed the project is in the root of the repository.
project_path = "DamageInfoPlugin"

# The changelog for this version. Will be shown in-game, as well on the Goat Place Discord.
changelog = """\
		Update for KR\
		"""
