[plugin]
repository = "https://github.com/dohwaplugins/DamageInfoPlugin.git"
commit = "e83a31ba1bd5cef7375517a51b2069c5c6ba9f4c"
owners = [
    "KangDohwa",
    "lmcintyre",
]
project_path = "DamageInfoPlugin"
