[plugin]
repository = "https://github.com/dohwaplugins/Distance.git"
commit = "80e541ecef38555b7a5d2860ffb797a4f98b3b7f"
owners = [
    "KangDohwa",
    "PunishedPineapple",
]
project_path = "Distance"
changelog = '''
- Added distance-based fading to text widgets and nameplate distances
- Added offsets by object type to nameplate distances.
- Minor config UI improvements.

Also contains the following differences that were previously only in the testing branch:
- Added a custom arcs feature to match custom widgets.
- Rewrote config UI.
- Added job filters to all distance displays.
- Added a filter for in and out of instance.
- Applied other filter types to displays that did not have them.
- Improved nameplate node setup to more closely match the base game.
- Fixed a bug that caused nameplate text nodes to not be properly cleaned up during plugin unload.
- Improved logging.
- Significant code cleanup and reorganization.
'''