[plugin]
repository = "https://github.com/dohwaplugins/ChillFrames.git"

# The commit to check out and build from the repository.
commit = "e7cb4d212de16978dbc7a9a9f5ac345b6950dbdd"

# The people authorised to update this manifest (e.g. who can deploy updates). These are GitHub usernames.
owners = [
    "KangDohwa"
]

# Optional: where your project/csproj is located within the repository.
# If empty or unspecified, it will be assumed the project is in the root of the repository.
project_path = "ChillFrames"

# The changelog for this version. Will be shown in-game, as well on the Goat Place Discord.
changelog = """\
		Update for KR\
		"""
