[plugin]
repository = "https://github.com/dohwaplugins/Dalamud.RichPresence.git"
commit = "6abfdd7a8973061162fb607e202649dd3e1f2c1c"
owners = [
    "KangDohwa",
    "goaaats",
    "reiichi001",
]
project_path = "Dalamud.RichPresence"
changelog = """
API 9 support. (Thank you NPittinger)

New features:
- Turn off rich presence when AFK (thank you sersorrel)
"""